<a href="https://colab.research.google.com/github/sharanyamp24-design/Severity_Prediction-/blob/main/GenAILAB1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Day1 Project

In [1]:
#downloading synthetic Medical Triage Priority Dataset from Kaggle into #content/data/raw

!pip install -q kaggle

In [2]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"sharanyamp","key":"6815e9dfd32d2500cdd6ec1f710cd5a9"}'}

In [3]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [4]:
!mkdir -p /content/data/raw

In [5]:
!kaggle datasets download -d azam897/synapse-dataset-of-symptoms-and-demographics -p /content/data/raw

Dataset URL: https://www.kaggle.com/datasets/azam897/synapse-dataset-of-symptoms-and-demographics
License(s): apache-2.0
Downloading synapse-dataset-of-symptoms-and-demographics.zip to /content/data/raw
100% 627k/627k [00:01<00:00, 608kB/s]

In [6]:
!unzip /content/data/raw/*.zip -d /content/data/raw

Archive:  /content/data/raw/synapse-dataset-of-symptoms-and-demographics.zip
  inflating: /content/data/raw/SYNAPSE_An Expert Annotated Dataset of Patient symptoms and Demographics.csv

In [7]:
!ls /content/data/raw

'SYNAPSE_An Expert Annotated Dataset of Patient symptoms and Demographics.csv'
 synapse-dataset-of-symptoms-and-demographics.zip

In [8]:
import pandas as pd

df = pd.read_csv('/content/data/raw/Synapse_Dataset.csv')
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '/content/data/raw/Synapse_Dataset.csv'

In [9]:
!ls /content/data/raw

'SYNAPSE_An Expert Annotated Dataset of Patient symptoms and Demographics.csv'
 synapse-dataset-of-symptoms-and-demographics.zip

In [10]:
import os
os.listdir('/content/data/raw')

['synapse-dataset-of-symptoms-and-demographics.zip',
 'SYNAPSE_An Expert Annotated Dataset of Patient symptoms and Demographics.csv']

In [11]:
import pandas as pd

df = pd.read_csv('/content/data/raw/SYNAPSE_An Expert Annotated Dataset of Patient symptoms and Demographics.csv')
df.head()

,Symptoms,Gender,Age,Duration,Severity,Final Recommendation
0,"Unwanted weight loss, Mouth sore, Persistent m...",Male,6-15 years,Greater than 3 days,Severe,Doctor Consultation
1,"Feeling tired, Shortness breath, Blue skin col...",Female,below 5 years,Greater than 3 days,Severe,Doctor Consultation
2,"False beliefs, Seeing, hearing things are not ...",Male,6-15 years,Greater than 3 days,Mild,Doctor Consultation
3,"Chest pain, Shortness breath, Fast heart rate,...",Female,above 45 years,Greater than 3 days,Moderate,Doctor Consultation
4,"fever, vaginal bleeding, painful urination, di...",Female,below 5 years,Less than 3 days,Severe,Doctor Consultation

In [12]:
!ls /content/data/raw

'SYNAPSE_An Expert Annotated Dataset of Patient symptoms and Demographics.csv'
 synapse-dataset-of-symptoms-and-demographics.zip

In [13]:
df.shape

(130637, 6)

# gg

In [14]:
print("Shape:", df.shape)
print("\nColumns:\n", df.columns)
print("\nInfo:")
print(df.info())
print("\nMissing Values:\n", df.isnull().sum())
print("\nFirst 5 Rows:")
display(df.head())

Shape: (130637, 6)

Columns:
 Index(['Symptoms', 'Gender', 'Age', 'Duration', 'Severity',
       'Final Recommendation'],
      dtype='object')

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130637 entries, 0 to 130636
Data columns (total 6 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Symptoms              130637 non-null  object
 1   Gender                130637 non-null  object
 2   Age                   130637 non-null  object
 3   Duration              130637 non-null  object
 4   Severity              130637 non-null  object
 5   Final Recommendation  130637 non-null  object
dtypes: object(6)
memory usage: 6.0+ MB
None

Missing Values:
 Symptoms                0
Gender                  0
Age                     0
Duration                0
Severity                0
Final Recommendation    0
dtype: int64

First 5 Rows:

,Symptoms,Gender,Age,Duration,Severity,Final Recommendation
0,"Unwanted weight loss, Mouth sore, Persistent m...",Male,6-15 years,Greater than 3 days,Severe,Doctor Consultation
1,"Feeling tired, Shortness breath, Blue skin col...",Female,below 5 years,Greater than 3 days,Severe,Doctor Consultation
2,"False beliefs, Seeing, hearing things are not ...",Male,6-15 years,Greater than 3 days,Mild,Doctor Consultation
3,"Chest pain, Shortness breath, Fast heart rate,...",Female,above 45 years,Greater than 3 days,Moderate,Doctor Consultation
4,"fever, vaginal bleeding, painful urination, di...",Female,below 5 years,Less than 3 days,Severe,Doctor Consultation

In [15]:
import os

# Create train folder
os.makedirs('/content/train', exist_ok=True)

# Extract first 10,000 rows
train_df = df.head(10000)

# Save as CSV
train_df.to_csv('/content/train/full_data.csv', index=False)

print("Saved successfully!")

Saved successfully!

In [16]:
!ls /content/train

full_data.csv

In [17]:
check_df = pd.read_csv('/content/train/full_data.csv')
check_df.shape

(10000, 6)

In [18]:
import os

# Create test folder
os.makedirs('/content/test', exist_ok=True)

# Extract first 2,000 rows
test_df = df.head(2000)

# Save as CSV
test_df.to_csv('/content/test/test_data.csv', index=False)

print("Saved successfully!")

Saved successfully!

In [19]:
!ls /content/test

test_data.csv

In [20]:
check_df = pd.read_csv('/content/test/test_data.csv')
check_df.shape

(2000, 6)

In [21]:
import pandas as pd

# Load test dataset
test_df = pd.read_csv('/content/test/test_data.csv')

# Remove severity column
test_df = test_df.drop(columns=['severity'])

# Save updated file
test_df.to_csv('/content/test/test_data.csv', index=False)

print("severity column removed successfully!")

KeyError: "['severity'] not found in axis"

In [22]:
# Remove column containing 'severity'
test_df = test_df.drop(
    columns=[col for col in test_df.columns if col.strip().lower() == 'severity']
)

# Save updated file
test_df.to_csv('/content/test/test_data.csv', index=False)

print("Severity column removed successfully!")

Severity column removed successfully!

In [23]:
test_df.columns

Index(['Symptoms', 'Gender', 'Age', 'Duration', 'Final Recommendation'], dtype='object')